print("Hello John")
print(34 + 26)
print(36 + 54 + 60)
print("kashkid")
print("Bett")
print("Lenox")
print("Kering")
print(60 - 40)
print("ng'ang'a")
print('and the  lawyer said "leave now"')
print(180/360)